Feature db wuyuwin
SOA-04/leaf-api pull request #51
Opened 2024-10-26 05:34 UTC by Wuyuwin

fix rubocop error except rake file namespace: db block is too long

2024-10-26 06:12 UTC, pedestrianlove requested changes

2024-10-26 06:12 UTC, pedestrianlove commented on db/migrations/003_update_location_table.rb
這個其實只要改前面的location table的migration就好。(反正我們現在的app也沒有客戶的資料要顧XD)

2024-10-26 17:46 UTC, pedestrianlove requested changes

2024-10-26 17:46 UTC, pedestrianlove commented on db/migrations/002_create_trips_table.rb
如果可以直接改這個檔案的話，是不是可以拿掉第三個migration檔案、直接修改第一個migration的錯字?

2024-10-26 17:46 UTC, pedestrianlove commented on spec/helpers/vcr_helper.rb
這個我其實看不太懂耶，為什麼要改這個檔案啊?

2024-10-26 22:11 UTC, Wuyuwin commented on db/migrations/002_create_trips_table.rb
是可以 只是老師不是說不要動第一個嗎？所以我就沒動了

2024-10-26 22:11 UTC, Wuyuwin commented on spec/helpers/vcr_helper.rb
我跑reek的時候有warning

2024-10-27 00:23 UTC, pedestrianlove commented on db/migrations/002_create_trips_table.rb
老師說不要動的原因是因為怕會動到客戶的資料庫內容，但我們現在還在內部開發，其實沒有差。
而且如果migration檔案增加，雖然會有一樣的資料庫建表效果，但也會讓migration檔案的可讀性變差。

2024-10-27 00:37 UTC, pedestrianlove commented on spec/helpers/vcr_helper.rb
Sorry, 我沒有注意到到老師的 `.reek.yml`[有改](https://github.com/ISS-SOA/soa2024-codepraise/blob/feature-database/.reek.yml)，那就這樣吧。

2024-10-27 00:47 UTC, pedestrianlove commented on db/migrations/002_create_trips_table.rb
(我們連main都還沒merge進去呢)

2024-10-27 00:56 UTC, pedestrianlove approved these changes

2024-10-27 00:57 UTC, merged